import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

const kanit = Kanit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <div className="min-h-screen flex flex-col">
          <Header/>
          {children}
          <footer className="footer footer-center p-4 bg-base-300 text-base-center">
            <p>Copyright @ 2024 - All right reserved by Nextjs App</p>

          </footer>
        </div>
        </body>
    </html>
  );
}
