// import type { Metadata } from "next";
// import { Kanit } from "next/font/google";
// import "./globals.css";
// import Header from "@/components/Header/Header";

// const kanit = Kanit({
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function FrontLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <main className="flex-grow container mx-auto px-4">
    {children}
   </main>
  );
}
